markdown: kramdown
pygments: true
permalink: /posts/:title
title: "Clojure Web Development"
production_url: http://clojurewebdev.com
description: "Your resource for learning how to do web development with Clojure."
disqus_shortname: clojurewebdev
# analytics: UA-32899481-1
# gauges: 50f2b533613f5d7c8000000c
author:
  name: Clinton Dreisbach
  github: cndreisbach
  twitter: cndreisbach
  email: crnixon+cljwww@gmail.com
